env_kwargs:
  fps_limit: 60
  laps_per_episode: 2
  max_steps_per_episode: 2000
  forward_range: [0.03, 0.2]
  turn_range: [-0.4, 0.4]

actor:
  kwargs:
    input_fc_layer_params: null
    lstm_size: [128]
    output_fc_layer_params: [128]
  learning_rate: 0.0001

critic:
  kwargs:
    observation_fc_layer_params: null
    action_fc_layer_params: [128]
    joint_fc_layer_params: null
    lstm_size: [128]
    output_fc_layer_params: [128]
  learning_rate: 0.001

target_updates_per_epoch: 1
ddpg_kwargs:
  target_update_tau: 0.01
  gamma: 0.99
  ou_stddev: 0.2
  ou_damping: 0.1
  summarize_grads_and_vars: true
  debug_summaries: false

num_epochs: 200
num_train_envs: 6
num_eval_envs: 2

train_batches_per_epoch: 40
collect_batches_per_epoch: 1
initial_collect_batches: 19
num_eval_episodes: 2
eval_interval: 120

train_sequence_length: 120
batch_size: 64
replay_buffer_max_length: 400_000
use_tf_functions: true
