env_kwargs:
  fps_limit: 60
  laps_per_episode: 1
  max_env_steps_per_episode: 4000
  forward_range: [0.02, 0.1]
  turn_range: [-1.0, 1.0]

actor:
  learning_rate: 0.0001
  kwargs:
    input_fc_layer_params: [512, 256]
    lstm_size: [256]
    output_fc_layer_params: [512, 256]

critic:
  learning_rate: 0.001
  kwargs:
    observation_fc_layer_params: [512]
    action_fc_layer_params: [512]
    joint_fc_layer_params: [128]
    lstm_size: [256]
    output_fc_layer_params: [512, 256]

target_updates_per_epoch: 1
ddpg_kwargs:
  target_update_tau: 0.002
  gamma: 0.99
  ou_stddev: 0.05
  ou_damping: 0.05
  summarize_grads_and_vars: true
  debug_summaries: false

max_num_epochs: 1000
num_train_envs: 6
num_eval_envs: 1

train_batches_per_epoch: 10
collect_batches_per_epoch: 2
initial_collect_batches: 8
num_eval_episodes: 2
eval_interval: 50

train_sequence_length: 100
batch_size: 64
replay_buffer_max_length: 5_000_000
use_tf_functions: true

checkpoint_interval: 1000
max_checkpoints_to_keep: 20
