actor_fc_layers:
- 600
- 400
- 200
actor_lstm_size:
- 200
actor_output_fc_layers:
- 200
- 100
- 50
- 20

critic_joint_fc_layers:
- 300
critic_lstm_size:
- 200
critic_obs_fc_layers:
- 400
- 200
critic_output_fc_layers:
- 200
- 100
- 50
- 20

cache_fill_episodes: 6

batch_size: 64
collect_episodes_per_iteration: 6
initial_collect_episodes: 24
num_iterations: 200
num_parallel_envs: 6
replay_buffer_capacity: 1000000
train_sequence_length: 30
train_steps_per_iteration: 100

actor_learning_rate: 0.0001
critic_learning_rate: 0.001
gamma: 0.99
ou_damping: 0.15
ou_stddev: 0.2
reward_scale_factor: 1.0
target_update_period: 1
target_update_tau: 0.01

use_tf_functions: true
debug_summaries: true
eval_interval: 500
log_interval: 500
num_eval_episodes: 1
save_interval: 3000
summaries_flush_secs: 10
summarize_grads_and_vars: true
summary_interval: 500
