actor:
  kwargs:
    input_fc_layer_params: [256]
    lstm_size: [512]
    output_fc_layer_params: [256, 128]
  learning_rate: 0.0001

critic:
  kwargs:
    joint_fc_layer_params: [256]
    lstm_size: [512]
    observation_fc_layer_params: [256]
    output_fc_layer_params: [256, 128]
  learning_rate: 0.001

num_epochs: 200
num_train_envs: 6
num_eval_envs: 2
train_batches_per_epoch: 10
collect_batches_per_epoch: 2
initial_collect_batches: 10

train_sequence_length: 60
batch_size: 64
replay_buffer_max_length: 400_000
num_eval_episodes: 8

use_tf_functions: true
