env_kwargs:
  fps_limit: 60
  laps_per_episode: 2
  max_env_steps_per_episode: 4000
  forward_range: [0.01, 0.1]
  turn_range: [-0.8, 0.8]

actor:
  learning_rate: 0.0001
  kwargs:
    input_fc_layer_params: [512, 256]
    lstm_size: [64]
    output_fc_layer_params: [512, 256]

critic:
  learning_rate: 0.001
  kwargs:
    observation_fc_layer_params: [512]
    action_fc_layer_params: [512]
    joint_fc_layer_params: [128]
    lstm_size: [64]
    output_fc_layer_params: [512, 256]

target_updates_per_epoch: 1
ddpg_kwargs:
  target_update_tau: 0.005
  gamma: 0.99
  ou_stddev: 0.05
  ou_damping: 0.05
  summarize_grads_and_vars: true
  debug_summaries: false

max_num_epochs: 1000
num_train_envs: 6
num_eval_envs: 1

train_batches_per_epoch: 20
collect_batches_per_epoch: 4
initial_collect_batches: 16
num_eval_episodes: 2
eval_interval: 120

train_sequence_length: 20
batch_size: 64
replay_buffer_max_length: 1_000_000
use_tf_functions: true

checkpoint_interval: 1000
max_checkpoints_to_keep: 20
